# Generated by Django 5.2.4 on 2025-07-28 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_seats', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
                'db_table': 'hall',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'SeatCategory',
                'verbose_name_plural': 'SeatCategorys',
                'db_table': 'seatcategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Theater',
                'verbose_name_plural': 'Theaters',
                'db_table': 'theater',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SeatPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('row', models.BigIntegerField()),
                ('call', models.BigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seatcategory')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
            ],
            options={
                'verbose_name': 'SeatePlace',
                'verbose_name_plural': 'SeatePlaces',
                'db_table': 'seateplace',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.theater'),
        ),
    ]
