# Generated by Django 5.2.4 on 2025-07-28 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_seats', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
                'db_table': 'hall',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Theater',
                'verbose_name_plural': 'Theaters',
                'db_table': 'theater',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing_time', models.TimeField()),
                ('showing_date', models.DateField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
                'db_table': 'show',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.theater'),
        ),
    ]
